# Generated by Django 3.1 on 2024-08-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20240801_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市信息表'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
